### ISSUE TITLE
Meetup SP

### ISSUE THREAD

**Issue by khaosdoctor** [training-center/meetups#1]
Criei aqui a issue para deixar uma base, ainda estamos sem muitas informações mas assim que eu tiver tudo eu já vou colocar aqui

**Comment by ftonato** [comment]
@khaosdoctor não sei exatamente como está a discussão sobre a organização dos _meetups_, mas há algo que pode [ser encontrado aqui também](https://github.com/training-center/sobre/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20meetup) e onde outrora deixei [minha opinião](https://github.com/training-center/sobre/issues/7).

Talvez possamos criar uma _issue_ para explicar aos demais como tudo deve funcionar.

***Nota:** Estou organizando [um _meetup_ informal sem vínculo com o _CT_](https://github.com/ftonato/DEV-SL-meetup), e que segue um formato que eu resolvi inventar, talvez seja uma coisa legal de se manter sobre cada encontro/edição e enfim. Caso queiram discutir sobre isso, estou aqui para ajudar...

**Comment by khaosdoctor** [comment]
sim sim @ftonato, é a mesma coisa, eu abri essa issue porque é algo muito mais próximo que vamos ter daqui a algumas semanas talvez. Essas issues são mais gerais
