### ISSUE TITLE
Temas para o próximo Meetup [SP]

### ISSUE THREAD

**Issue by woliveiras** [training-center/meetups#13]
Essa issue serve para levantarmos temas para discussão durante nosso Meetup, que será em formato de mesa redonda, onde todos iremos discutir sobre o assunto e explorar tópicos, trocar experiências, etc.

Eu acredito que esse é o melhor formato de Meetup possível, pois eu aprendi muito através disso. Será um teste para o Training Center e, caso vocês curtam, teremos outros do mesmo tipo.

## Quero postar um assunto

Você pode comentar aqui nessa issue o assunto a ser discutido.

Ex.: `poderíamos discutir sobre carreira` ou `gostaria de saber como cria uma aplicação do zero`

Pode ser qualquer assunto, até mesmo discutir sobre algo ruim que esteja acontecendo contigo.

## Votação

Serão escolhidos 2 assuntos dos votados aqui.

E para votar você deve clicar no joinha (:+1:) aqui no GitHub.

![selection_006](https://user-images.githubusercontent.com/4243601/31190656-17376b7e-a912-11e7-98dd-ec3f6c5207a6.jpg)

**Comment by sonymaia-luizalabs** [comment]
Podemos falar sobre como aplicar TDD.. quais suas dificuldade e quais seus benefícios..e ver quem está usando essa prática

**Comment by sonymaia-luizalabs** [comment]
Métodos ageis e suas cerimônias realmente ajudam no desenvolvimento de software ou é só mais uma barreira? 
Um tema seria: métodos ageis na visão dos desenvolvedores

**Comment by jonathan-santos** [comment]
Que tal programação funcional?

**Comment by jonathan-santos** [comment]
Criando e mantendo rotinas de estudos

**Comment by lflimeira** [comment]
IoT e o fantastico mundo "fora dos computadores".

**Comment by jonathan-santos** [comment]
Melhorando a produtividade

**Comment by khaosdoctor** [comment]
Microserviços

**Comment by khaosdoctor** [comment]
CI e CD na prática

**Comment by hjdesigner** [comment]
Como perder a vergonha para interagir com seu mentor e com o resto da comunidade.

**Comment by woliveiras** [comment]
Encerrando a votação, galera. 

Valeu pela participação de todos!
