### ISSUE TITLE
C4P para o Meetup SP #3

### ISSUE THREAD

**Issue by khaosdoctor** [training-center/meetups#15]
Para submeter uma palestra responda os seguintes tópicos:

- Título da palestra:
- Breve descrição:
- Tempo de duração:
- Nome completo: 
- Redes sociais: 
- Link para slides (se tiver): usuario (rede_social), usuario (rede_social)
- Precisa de algum equipamento (S/N)?
- Possui necessidades especiais (S/N)?
- Possui restrições alimentares (S/N)?

**Comment by khaosdoctor** [comment]
Inaugurando o tópico aqui.

- Título da palestra: **Kubernetes: Uma introdução à gerencia e criação de microserviços**
- Breve descrição: Nesta talk pretendo dar uma introdução sobre o que são microserviços, como utilizá-los e como fazer as comunicações entre eles utilizando o Kubernetes
- Tempo de duração: Chuto uns 30 min, se sobrar tempo um live coding
- Nome completo: Lucas Santos
- Redes sociais: tudo [neste link](lsantos.me)
- Link para slides (se tiver): http://lsantos.me
- Precisa de algum equipamento (S/N): S passador de slides
- Possui necessidades especiais (S/N): N
- Possui restrições alimentares (S/N): N

**Comment by lflimeira** [comment]
Título da palestra: PHP das Coisas
Breve descrição: Nesta talk pretendo falar sobre IoT e fazer uma introdução sobre utilização do PHP em IoT.
Tempo de duração: 20 minutos
Nome completo: Luiz Felipe de Oliva Limeira
Redes sociais: 
https://twitter.com/lflimeira02
https://github.com/lflimeira
Link para slides (se tiver):
Precisa de algum equipamento (S/N): S passador de slides
Possui necessidades especiais (S/N): N
Possui restrições alimentares (S/N): N

**Comment by woliveiras** [comment]
Como as pessoas irão votar, galera?

Com os likes de novo, né?

**Comment by lflimeira** [comment]
Isso... só colocar o joinha. 😃 mas por hora tem só o do @khaosdoctor que é 40 min e a minha que é 20. Acha que vale abrir para votação @woliveiras?

**Comment by alinebastos** [comment]
Acho que votação só se tiver mais que 3, né?

**Comment by khaosdoctor** [comment]
Sim, só se passar, mas ainda só se passar nas de 40 e de 20, porque temos espaço para 1 de 40 e 2 de 20. Então se tivermos só uma de 40 e 5 de 20 ai só as de 20 entram em votação e vice versa

**Comment by mmalaquiasdev** [comment]
Título da palestra: Spring Boot - Mais produtividade com Java
Breve descrição: Você sofre demais para começar um projeto java? Faz muitas configurações com XML? Tem que se preocupar com um servidor de aplicação? Então seus problemas acabaram! Com Spring Boot conseguimos criar uma aplicação/API e rapidamente colocá-la no ar. Nessa palestra vamos entender como começar a utilizar essa nova ferramentda da Pivotal.
Tempo de duração: 20 min
Nome completo: Mateus Oliveira Malaquias
Redes sociais: 
 - Twitter: www.twitter.com/mmalaquiasdev
 - Github: https://github.com/mmalaquiasdev
- Linkedin: https://www.linkedin.com/in/mateus-malaquias-692532b5/
Link para slides (se tiver):
Precisa de algum equipamento (S/N)? S passador de slides
Possui necessidades especiais (S/N)? N
Possui restrições alimentares (S/N)? N

**Comment by mmalaquiasdev** [comment]
Título da palestra: Java não esta morto
Breve descrição: Para você o Java morreu? Então para o mercado não. O Java 9 acabou de ser lançado, que tal a gente ver algumas de suas novidades.
Tempo de duração: 20 min
Nome completo: Mateus Oliveira Malaquias
Redes sociais:

Twitter: www.twitter.com/mmalaquiasdev
Github: https://github.com/mmalaquiasdev
Linkedin: https://www.linkedin.com/in/mateus-malaquias-692532b5/
Link para slides (se tiver):
Precisa de algum equipamento (S/N)? S passador de slides
Possui necessidades especiais (S/N)? N
Possui restrições alimentares (S/N)? N

**Comment by mmalaquiasdev** [comment]
Título da palestra: Java S2 Lambdas Expressions
Breve descrição: O que são Lambdas expressions e para que podemos usa-las no Java? Nessa palestra vamos entender um pouco sobre Lambda expressions e como podemos utiliza-as no dia-a-dia em nossos projetos Java.
Tempo de duração: 20 min
Nome completo: Mateus Oliveira Malaquias
Redes sociais:

Twitter: www.twitter.com/mmalaquiasdev
Github: https://github.com/mmalaquiasdev
Linkedin: https://www.linkedin.com/in/mateus-malaquias-692532b5/
Link para slides (se tiver):
Precisa de algum equipamento (S/N)? S passador de slides
Possui necessidades especiais (S/N)? N
Possui restrições alimentares (S/N)? N

**Comment by mosiahvuxs** [comment]
Spring Boot - Mais produtividade com Java

**Comment by lflimeira** [comment]
@mosiahvuxs ???

**Comment by mosiahvuxs** [comment]
@lflimeira eu comentei achando que o post seria contabilizado como voto, mas já exclui e votei corretamente!

**Comment by lflimeira** [comment]
Ahh blz... obrigado por participar 😃

**Comment by Kirmayrtomaz** [comment]
Título da palestra: Trabalhando com  cache com Redis e nodejs
Breve descrição: Abordagem que explica o conceitos de cache nas pontas da aplicação, a escolha de Redis no projeto, analise do que o mercado está utilizando e como implementar isso numa aplicação
Tempo de duração: 25 min
Nome completo: Kirmayr Roberto Tomaz Costa

Twitter: https://twitter.com/kirmayrtomaz
Github: https://github.com/kirmayrtomaz
Linkedin:https://www.linkedin.com/in/kirmayrtomaz/
Link para slides (se tiver):
Precisa de algum equipamento (S/N)? S 
Possui necessidades especiais (S/N)? N
Possui restrições alimentares (S/N)? N

**Comment by Kirmayrtomaz** [comment]
Título da palestra: Criando uma api em nodejs
Breve descrição: Criar uma api em node.js não é um simples hello world. Nessa palestra iremos mostrar os pontos importantes que devem ser feitos como documentação, lint, teste unitário, teste de integração, utilizar docker e outros.
Tempo de duração: 30 min
Nome completo: Kirmayr Roberto Tomaz Costa:

Twitter: https://twitter.com/kirmayrtomaz
Github: https://github.com/kirmayrtomaz
Linkedin:https://www.linkedin.com/in/kirmayrtomaz/
Link para slides (se tiver):
Precisa de algum equipamento (S/N)? S 
Possui necessidades especiais (S/N)? N
Possui restrições alimentares (S/N)? N

**Comment by lbighetti** [comment]
Para submeter uma palestra responda os seguintes tópicos:

Título da palestra: **Como Conseguir Trabalho no Exterior - Guia de um Expatriado**
Breve descrição: O que é necessário para conseguir um trabalho no exterior ? Porquê poucas pessoas conseguem e muitas não ? Qual o segredo ?
Nesta talk vou responder estas e outras perguntas, compartilhar como eu consegui um trabalho na Alemanha e mostrar quais os passos necessários para quem tem esse objetivo.
Tempo de duração: 40 min
Nome completo: Leandro Moraes Bighetti
Redes sociais:
* https://www.linkedin.com/in/leandrobighetti/
* https://github.com/lbighetti
* https://twitter.com/leandrobighetti

Link para slides (se tiver):
Precisa de algum equipamento (S/N)? S passador de slides
Possui necessidades especiais (S/N)? N
Possui restrições alimentares (S/N)? S - Sou Vegano

**Comment by Polovinsky** [comment]
Título da palestra: **Programação Funcional com Java 8**

Breve descrição: Nesta talk vamos ver um pouco de Programação Funcional com Java 8. Uso de Lambda Expression, Method Reference, Interface Funcional e etc..
Tempo de duração: 20 min
Nome completo: Diego Polovinsky
Redes sociais:

- Twitter: https://twitter.com/diegopolovinsky
- Github: https://github.com/Polovinsky

Link para slides (se tiver):

- Precisa de algum equipamento (S/N)? S
- Wifi
- Microfone
- Retroprojetor com entrada HDMI ou adaptador HDMI para VGA + cabo HDMI

Possui necessidades especiais (S/N)? N
Possui restrições alimentares (S/N)? N

**Comment by lflimeira** [comment]
Pessoal, fechando as votações =)

**Comment by lflimeira** [comment]
O mais votados foram: 
@mmalaquiasdev: Spring Boot - Mais produtividade com Java
@Polovinsky: Programação Funcional com Java 8
@lbighetti: Como Conseguir Trabalho no Exterior - Guia de um Expatriado

Preciso da confirmação dos mais votados. 😄 

E quanto as outras talks que foram enviadas, nós vamos mantê-las para os talks futuros se todos concordarem =) \o/

**Comment by mmalaquiasdev** [comment]
@lflimeira to confirmado \o/

**Comment by Polovinsky** [comment]
@lflimeira confirmado!

**Comment by lbighetti** [comment]
@lflimeira confirmado!

**Comment by lflimeira** [comment]
Opa, então fechou... vou colocar no meetup pessoal 😆

**Comment by khaosdoctor** [comment]
Fechando a issue aqui galera!

**Comment by lflimeira** [comment]
@Polovinsky vc está como não confirmado no meetup.

**Comment by mmalaquiasdev** [comment]
@iflimeira eu também -.-

**Comment by lflimeira** [comment]
Eita, mas pq? Vcs tiraram a confirmação?

**Comment by lflimeira** [comment]
O @lbighetti tbm n está. Eu abri mais vagas lá, vcs podem confirmar?

**Comment by mmalaquiasdev** [comment]
É que nao tinha vaga quando fui me inscrever, acabei entrando na lista de espera... Ai eu pensei que era OK

**Comment by mmalaquiasdev** [comment]
Feito!

**Comment by lflimeira** [comment]
Ata rsrsrs Tranquilo 😄

**Comment by Polovinsky** [comment]
Ah pensei que não precisava eu estar na lista. Posso me inscrever de novo?

**Comment by Polovinsky** [comment]
Feito!

**Comment by lflimeira** [comment]
Pode sim. 😄

**Comment by lflimeira** [comment]
Obrigado pessoal, vou fechar novamente a issue, e obrigado aos palestrantes e a todos que mandaram palestras. 😄
