### ISSUE TITLE
Meetup CWB #1

### ISSUE THREAD

**Issue by BritoMari** [training-center/meetups#17]
Essa issue é pra centralizar todas as nossas ideias, dúvidas ou sugestões para a organização do primeiro meetup do training center em curitiba.

**O que precisamos definir?**

- [x] Formato (palestras/mesa redonda/workshops/etc)
- [x] Local (precisamos de um local de fácil acesso)
- [x] Cronograma 

Por enquanto é só, conforme andamento vamos vendo o que mais for preciso.

**Comment by BritoMari** [comment]
@nandomoreirame você tinha comentado sobre um local, achei legal, mas acho que é meio longe do centro e isso pode acabar dificultando o acesso.
Por enquanto vamos pensando em outras opções.

O que vocês acham de entrar em contato com universidades pra ceder um auditório ou algo do tipo?

**Comment by woliveiras** [comment]
Dos nossos dois que fizemos, tivemos os seguintes feedback's:

**primeiro**

- demoramos muito para abrir o evento, pois chegaram poucas pessoas e ficamos com receio de ter que repetir tudo pra quem viesse depois
- as palestras foram muito boas
- o esquema de lightning talk é muito engajador

**segundo**

-melhor feedback das pessoas que participaram, pois fizemos em formato de mesa redonda e todo mundo pode participar ao menos um pouco
- foi pouca gente (12 pessoas) o que possibilitou uma interação muito maior

**no geral**

- nos primeiros eventos vocês vão conseguir medir a taxa de abandono (gente que marca que vai, porém não vai), anote isso para tirar uma porcentagem e quando abrir os próximos eventos abrir sempre com essa porcentagem a mais de espaço par que as pessoas que realmente vão não fiquem sem espaço para entrar na fila de espera por causa das outras pessoas
- abrir o evento para ingressar (abrir para as pessoas se inscreverem) muito antes da data é ruim, se possível abrir com alguns dias de antecedência, pois a taxa de abandono será menor

**Comment by marcelabomfim** [comment]
Obrigada pelas dicas @woliveiras

**Comment by FernandaBernardo** [comment]
Só para falar de quando abrir o evento para inscrição... eu conheço um meetup que abre um ou dois dias antes do evento, e é impressionante, é quase 100% de presença. Acho que de 40 inscritos foram 36 pessoas. Então, se tivermos essa conduta desde o início, as pessoas já saberão como funcionamos.

**Comment by maaryhabad** [comment]
Gente, posso ver com o pessoal da PUC se eles cedem um auditório! (esse é 98% de chance de conseguir).

Se der, eu posso palestrar sobre como vim parar na programação (minha formação é em música HAHAHAH)

**Comment by maaryhabad** [comment]
E acho que o ideal seria marcar uma reunião pra ver detalhes da organização e etc! 

Sobre inscrições, eu faço parte da Staff da Global Game Jam Curitiba e tenho certa experiência com isso. Como tenho um contato bem próximo com a PUC posso arranjar uma reunião com o organizador geral pra gente ter apoio da universidade :)

**Comment by BritoMari** [comment]
Veja sim, assim que conseguir marcar a reunião nos avise, pode ser qualquer dia de semana a noite.

**Comment by khaosdoctor** [comment]
Esse meetup já está em andamento não é @BritoMari?

**Comment by marcelabomfim** [comment]
Sim sim @khaosdoctor, valeu pelo lembrete.
Está marcado para o dia 15/12 já abrimos para inscrições aqui: https://www.meetup.com/pt-BR/Training-Center-CWB/events/245339153/

Então só pra fechar:
**Formato:** Mesa redonda
**Local:** Liquori Café - R. Comendador Araújo, 534, Centro, Curitiba
**Cronograma:** Terá início as 19h com previsão de duração até 21h, temos alguns assuntos na pauta para ir discutindo com o pessoal, que são: 
- Apresentação de todos, o que faz estuda/trabalha, de onde vem, como conheceu o TC ...
- Porquê TI / Como chegou nessa escolha?
- Escolhi fazer TI, e agora?
- Quais foram as suas maiores dificuldades na carreira?
- Fazer ou não uma faculdade? EAD? 
- Como conseguir meu primeiro emprego?
- Já tenho um emprego mas sinto que não estou evoluindo, o que fazer?
- Como podemos melhorar a diversidade na área, incluir pessoas de minoria?
