### ISSUE TITLE
C4P meetup TC Talks SP #5

### ISSUE THREAD

**Issue by lflimeira** [training-center/meetups#20]
Para submeter uma palestra responda os seguintes tópicos:

- Título da palestra:
- Resumo da palestra:
- Duração:

- Nome completo: 
- Redes sociais: 
- Link para slides (se tiver): usuario (rede_social), usuario (rede_social)
- Precisa de algum equipamento (S/N)?
- Possui necessidades especiais (S/N)?
- Possui restrições alimentares (S/N)?

**Comment by alexandremalavasi** [comment]
**25 dicas de banco de dados para desenvolvedores - São Paulo - Capital**

Nome completo: Alexandre Malavasi
Redes sociais: @alemalavasi (Twitter), alexandremalavasi (Facebook), alexandremalavasi (Linkedin)
Link para slides: N/A
Precisa de algum equipamento (S/N)? N
Possui necessidades especiais (S/N)? N
Possui restrições alimentares (S/N) N

**Comment by DiegoPinho** [comment]
**Web scraping com Node.js e cheerio**

Nome completo: Diego Martins de Pinho
Redes sociais: @DiegoPinho (Twitter), diego.pinho.31(Facebook)
Link para slides: N/A
Precisa de algum equipamento (S/N)? N
Possui necessidades especiais (S/N)? N
Possui restrições alimentares (S/N) N

**Comment by lflimeira** [comment]
@alexandremalavasi e @DiegoPinho vcs podem complementar o comentário de vcs com as infos a seguir?

Título da palestra:
Resumo da palestra:
Duração:

Eu havia esquecido de colocar essas informações no modelo 😃

**Comment by gionaufal** [comment]
**Título da palestra: Como deixei uma carreira em marketing e me tornei um desenvolvedor**

Resumo da palestra: Minha jornada deixando uma carreira ascendente (mas que não me fazia feliz) em Marketing para me tornar um desenvolvedor web. Quais foram os recursos que utilizei para aprender, o que fiz de certo e errado, onde estou hoje e onde quero chegar.

Duração: ainda não sei direito, mas acho que consigo fazer em 15 minutos.

Nome completo: Giovanni Naufal Filippetti

Redes sociais: gionaufal (Twitter, Facebook, LinkedIn, GitHub) 

Link para slides (se tiver): N/A

Precisa de algum equipamento (S/N)? N

Possui necessidades especiais (S/N)? N

Possui restrições alimentares (S/N)? N

**Comment by Halfeld** [comment]
**Título da palestra:** Vue.js Reactive System
**Resumo da palestra:** Entender como funciona a reatividade (basicamente o data-binding) do Vue.js, comparar ele com outros frameworks front-end e no final da talk, vamos fazer a implementação de uma engine de data binding :D
**Duração:** 30m
**Nome completo:** Igor Luiz Halfeld
**Redes sociais:**
- [Linkedin](https://www.linkedin.com/in/igorhalfeld/)
- [Facebook](https://www.facebook.com/igorhalfeld)
- [Twitter](https://twitter.com/igorhalfeld)
- [Github](https://github.com/halfeld)  

**Link para slides:** [Google docs](https://docs.google.com/presentation/d/1wNl8vh5qUldkQ01aWRT-av6pw4MAHInEzh0ngNVsDGg/edit?usp=sharing)
**Precisa de algum equipamento (S/N)?** não
**Possui necessidades especiais (S/N)?** não
**Possui restrições alimentares (S/N)?** não

**Comment by mmalaquiasdev** [comment]
Título da palestra: NoSQL o mínimo que você precisa saber
Resumo da palestra: Fala-se muito sobre os bancos de dados NoSQL, principalmente MongoDB e Redis. Porém, pouca gente ainda conhece os conceitos por trás desse mercado. Nesta palestra, explicarei o mínimo que você precisa saber sobre o assunto. 
Duração: 30min
Nome completo: Mateus Malaquias
Redes sociais: https://twitter.com/mmalaquiasdev
Link para slides (se tiver): 
Precisa de algum equipamento (S/N): S, datashow;
Possui necessidades especiais (S/N)? N
Possui restrições alimentares (S/N)? N

**Comment by Polovinsky** [comment]
Título da palestra: **TDD - Teste antes de qualquer coisa.**
Resumo da palestra: Muito se fala sobre TDD, perguntas como: 
 * Como pensar no teste antes? 
 * TDD prejudica o design?
Esse talk quero mostrar como escrevo códigos usando TDD, e discutir um pouco estas questões que a prática tem gerado.

Duração: 30min
Nome completo: **Diego Rocha**
Redes sociais: Twitter **@diegopolovinsky**, GitHub **@polovinsky**
Link para slides (se tiver):
Precisa de algum equipamento (S/N): S, datashow, microfone;
Possui necessidades especiais (S/N)? N
Possui restrições alimentares (S/N)? N

**Comment by clebercampomori** [comment]
**Título da palestra:** REST não é simplesmente JSON: indo além com APIs REST
**Resumo da palestra:** Quantas vezes já ouvimos falar (ou até nós mesmos falamos) que alguém criou uma API REST somente pelo fato de esta entregar um JSON? Esse é um equívoco bem comum... Porém, é necessário saber que na verdade a utilização do REST não tem nenhuma relação direta com o JSON. Nesta palestra, procurarei explicar o que é afinal o tal do REST, a relação deste com o JSON e também falarei um pouco sobre a famigerada batalha XML x JSON, além de discutir um pouco sobre o protocolo HTTP.
**Duração:** Cerca de 30 minutos
**Nome completo:** Cleber Lopes Campomori
**Redes sociais:** Facebook: [https://www.facebook.com/cleber.campomori](https://www.facebook.com/cleber.campomori); LinkedIn: [https://www.linkedin.com/in/clebercampomori/](https://www.linkedin.com/in/clebercampomori/)
**Link para slides (se tiver):** [Aqui](https://drive.google.com/file/d/0B2A050iOMYNdOW1TMVJ3WDA0RjQ/view?usp=sharing). Versão da palestra feita para a Universidade Federal de Lavras.
**Precisa de algum equipamento (S/N)?** Um projetor HDMI
**Possui necessidades especiais (S/N)?** Não
**Possui restrições alimentares (S/N)?** Não

**Comment by robertoachar** [comment]
**Título da palestra**: Entenda tudo sobre Async/Await

**Resumo da palestra**: A ideia é apresentar o cenário completo para trabalhar com async/await, uma das novas funcionalidades do ES2017.

* Escrevendo uma função assíncrona com Promises
* Escrevendo uma função assíncrona com async/await
* Utilizando async/await com Promises
* Resolvendo ou rejeitando uma Promise com async/await
* Tratamento de erros com Throw Error()
* Tratamento de erros com try/catch
* Utilizando async/await com function expressions
* Entendendo o await
* IIFE - Immediately-Invoked Function Expression
* Utilizando async/await com classes
* Exportando uma classe com funções assíncronas
* Aguardando múltiplas requisições em sequência
* Aguardando múltiplas requisições simultâneas
* Aguardando múltiplas requisições simultâneas usando Promise.all()
* Usando o conceito de high-order function para tratar erros
* Usando high-order function no Express

**Duração**: 30 minutos

**Nome completo**: Roberto Achar

**Redes sociais**: Twitter (robertoachar), GitHub (robertoachar)

**Link para slides (se tiver)**:

Os slides serão construídos com base nesse artigo.

* Blog: [https://showmethecode.com.br/async-await/](https://showmethecode.com.br/async-await/)
* iMasters: [https://imasters.com.br/front-end/javascript/entenda-tudo-sobre-asyncawait/](https://imasters.com.br/front-end/javascript/entenda-tudo-sobre-asyncawait/)
* Repo: [https://github.com/robertoachar/async-await](https://github.com/robertoachar/async-await)

**Precisa de algum equipamento (S/N)?** Projetor  
**Possui necessidades especiais (S/N)?** Não  
**Possui restrições alimentares (S/N)?** Não
