### ISSUE TITLE
Meetup CE

### ISSUE THREAD

**Issue by virginiarcruz** [training-center/meetups#4]
Criei a issue para iniciar a ideia do Meetup em Fortaleza.

**Comment by lflimeira** [comment]
@virginiarcruz  tudo bem? Esse repositório é mais para quando o meetup já estiver criado. Para levantar a discussão com o pessoal e criar o meetup em si, estamos utilizando o repositório https://github.com/training-center/sobre, que já possuí uma issue para o CE https://github.com/training-center/sobre/issues/24. Você pode colocar suas ideias lá e já combinar com o pessoal para fazer esse meetup sair do papel :smile:

**Comment by lflimeira** [comment]
Vou fechar essa issue para deixar centralizado lá, qualquer coisa nós reabrimos ok?
