### ISSUE TITLE
(Talk) PWA: Progressive Web Apps - São Paulo - Capital

### ISSUE THREAD

**Issue by maicongouveia** [training-center/meetups#6]
- Nome completo: Maicon Soares Gouveia
- Redes sociais: @gouveiamaicon (twitter) 
- Link para slides: [www.maicongouveia.com.br/talk/pwa](www.maicongouveia.com.br/talk/pwa) (vão estar finalizados no dia 07/09/2017)
- Precisa de algum equipamento ? Sim. Projetor se possivel
- Possui necessidades especiais ? Não
- Possui restrições alimentares ? Não

**Comment by woliveiras** [comment]
Valeu, @maicongouveia!

**Comment by lflimeira** [comment]
@maicongouveia você concorda com nosso código de conduta https://github.com/training-center/sobre/blob/master/CONDUCT.md ?

Pergunto isso pois a palestra não pode violar nosso código de conduta, por tanto preciso que você esteja ciente e de acordo :smile:

**Comment by maicongouveia** [comment]
Eu concordo com o termos :)

Em 6 de set de 2017 1:35 PM, "Luiz Felipe de Oliva Limeira" <
notifications@github.com> escreveu:

**Comment by woliveiras** [comment]
Valeu pela talk, @maicongouveia!
